name: Release

on:
  push:
    branches: [master]

jobs:
  build-number:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}
      - name: Upload build number
        uses: actions/upload-artifact@v1
        with:
          name: BUILD_NUMBER
          path: BUILD_NUMBER

  android:
    needs: build-number
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Download build number
        uses: actions/download-artifact@v1
        with:
          name: BUILD_NUMBER
      - name: Restore build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Set build number
        run: |
          sed -i -e "1,/+1/s/+1/+$BUILD_NUMBER/" pubspec.yaml
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build appbundle
