name: Release

on:
  push:
    branches: [master]

jobs:
  build-number:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}
      - name: Upload build number
        uses: actions/upload-artifact@v1
        with:
          name: BUILD_NUMBER
          path: BUILD_NUMBER

  android:
    needs: build-number
    runs-on: ubuntu-latest

    steps:
      - name: Download build number
        uses: actions/download-artifact@v1
        with:
          name: BUILD_NUMBER
      - name: Restore build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Restore keystore
        run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - name: Set build number
        run: |
          sed -i -e "1,/+1/s/+1/+$BUILD_NUMBER/" pubspec.yaml
      - name: Set env vars
        run: |
          echo "SENTRY_DNS=$SENTRY_DNS" > .env
        env:
          SENTRY_DNS: ${{ secrets.SENTRY_DNS }}
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build appbundle
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.sliceitapp.sliceit
          releaseFile: build/app/outputs/bundle/release/app-release.aab
          track: internal
